---
# tasks file for roles/configure_nginx
- name: Get public IP address
  community.general.ipify_facts:
- name: Generate common name
  ansible.builtin.set_fact:
    server_cert_common_name: "{{ ipify_public_ip }}: Self-signed certificate"
  when: (server_cert_common_name is not defined) or (server_cert_common_name|length == 0)
- name: Generate list of alt names
  ansible.builtin.set_fact:
    server_cert_alt_names:
      - "IP:{{ ipify_public_ip }}"
      - "IP:127.0.0.1"
  when: (server_cert_alt_names is not defined) or (server_cert_alt_names|length == 0)
- name: Create server private key (RSA, 4096 bits)
  become: true
  community.crypto.openssl_privatekey:
    path: "{{ server_key_path }}/{{ server_key_name }}"
    passphrase: "{{ server_key_password | default(omit) }}"
- name: Create CSR for self-signed certificate
  become: true
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ server_key_path }}/{{ server_key_name }}"
    privatekey_passphrase: "{{ server_key_password | default(omit) }}"
    common_name: "{{ server_cert_common_name }}"
    organization_name: "{{ server_org_name }}"
    subject_alt_name: "{{ server_cert_alt_names }}"
    country_name: "{{ server_country_name }}"
    state_or_province_name: "{{ server_state_or_province_name }}"
    locality_name: "{{ server_locality_name }}"
  register: server_csr
  changed_when: false
- name: Create self-signed certificate
  become: true
  community.crypto.x509_certificate:
    path: "{{ server_cert_path }}/{{ server_cert_name }}"
    privatekey_path: "{{ server_key_path }}/{{ server_key_name }}"
    privatekey_passphrase: "{{ server_key_password | default(omit) }}"
    csr_content: "{{ server_csr.csr }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
- name: Generate client private key
  local_action:
    module: community.crypto.openssl_privatekey
    path: "{{ client_key_local_path }}/{{ client_key_name }}"
    passphrase: "{{ client_key_passphrase | default(omit) }}"
