---
# tasks file for roles/configure_mysql
- name: Install Python MySQL dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
      - pkg-config
- name: Install Python MySQL library
  ansible.builtin.pip:
    name: mysqlclient
