---
# tasks file for roles/configure_mysql
- name: Install Python MySQL dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
      - pkg-config
- name: Install Python MySQL library
  ansible.builtin.pip:
    name: mysqlclient
- name: Install MariaDB
  become: true
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  notify: Restart MySQL
- name: Start and Enable MySQL
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true
- name: Create root credential file
  become: true
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "u=rw,go="
- name: Set MySQL root password
  become: true
  community.mysql.mysql_user:
    host: localhost
    name: root
    password: "{{ mysql_root_password }}"
    state: present
