---
# tasks file for roles/configure_mysql
- name: Install Python MySQL dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
      - pkg-config
- name: Install Python MySQL library
  ansible.builtin.pip:
    name: mysqlclient
- name: Install MariaDB
  become: true
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  notify: Restart MySQL
- name: Start and Enable MySQL
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true
