---
# tasks file for roles/configure_wes_systemd
- name: Create the logfile directory
  become: true
  ansible.builtin.file:
    path: "{{ wes_log_directory }}"
    state: directory
    owner: cromwell
    group: cromwell
    mode: "u=rwx,go=rx"
- name: Create WES install directory
  become: true
  ansible.builtin.file:
    path: "{{ wes_install_directory }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"
- name: Download WES JAR to install directory
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/DNAstack/cromwell-wes-service/releases/download/{{ wes_version }}/cromwell-wes-service-{{ wes_version }}.jar"
    dest: "{{ wes_install_directory }}"
    owner: root
    group: root
    mode: "u=rw,go=r"
    backup: true
