---
# tasks file for roles/configure_cromwell_systemd
- name: Create the logfile directory
  become: true
  ansible.builtin.file:
    path: "{{ cromwell_log_directory }}"
    state: directory
    owner: cromwell
    group: cromwell
    mode: "u=rwx,go=rx"
- name: Create Cromwell install directory
  become: true
  ansible.builtin.file:
    path: "{{ cromwell_install_directory }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"
- name: Create Cromwell config directory
  become: true
  ansible.builtin.file:
    path: "{{ cromwell_config_directory }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"
- name: Create Cromwell job output directory
  become: true
  ansible.builtin.file:
    path: "{{ cromwell_job_output_directory }}"
    state: directory
    owner: cromwell
    group: cromwell
    mode: "ug=rw,o="
- name: Install Java
  become: true
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
- name: Download Cromwell JAR to install directory
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/broadinstitute/cromwell/releases/download/{{ cromwell_version }}/cromwell-{{ cromwell_version }}.jar"
    dest: "{{ cromwell_install_directory }}"
    owner: root
    group: root
    mode: "u=rw,go=r"
    backup: true
- name: Copy Cromwell config to config directory
  become: true
  ansible.builtin.template:
    src: cromwell-application.conf.j2
    dest: "{{ cromwell_config_directory }}/{{ cromwell_config_name }}"
    owner: root
    group: root
    mode: "u=rw,go=r"
- name: Install the SystemD service
  become: true
  ansible.builtin.template:
    src: cromwell.service.j2
    dest: /etc/systemd/system/cromwell.service
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: Reload Daemons
- name: Start and enable the cromwell service
  become: true
  ansible.builtin.systemd:
    name: cromwell.service
    state: started
    enabled: true
    daemon_reload: true
